config/routes.rb
Rails.application.routes.draw do
  root to: "students#index"
  resources :students
  resources :institutions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/institution.rb
class Institution < ApplicationRecord
    has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :institution

  validates_presence_of :full_name, :address, :dob, :institution
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :address, :phone)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:full_name, :address, :phone, :dob, :score, :institution_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/institutions/_form.html.erb
<div class="row">
  <%= form_with(model: institution, local: true, class: 'col-lg-4') do |form| %>
    <% if institution.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

        <ul>
        <% institution.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :address %>
      <%= form.text_area :address, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :phone %>
      <%= form.text_field :phone, class: "form-control" %>
    </div>

    <div class="mb-3 actions">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>  

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.address %></td>
        <td><%= institution.phone %></td>
        <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @institution.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @institution.phone %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentsDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid bg-primary">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">Student DB</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Add Student", new_student_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Add Institution", new_institution_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </nav>    
    </div>
    <div class="container">
      <%= yield %>
    </div>
    
    
  </body>
</html>

app/views/students/_form.html.erb
<div class="row">
  <%= form_with(model: student, local: true, class: 'col-lg-4') do |form| %>
    <% if student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group mb-3">
      <%= form.label :full_name %>™
      <%= form.text_field :full_name, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :address %>
      <%= form.text_area :address, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :mobile %>
      <%= form.text_field :mobile, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :dob, 'Date of birth' %>
      <%= form.date_field :dob, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :score %>
      <%= form.number_field :score, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :institution_id %>
      <%= form.select :institution_id, options_from_collection_for_select(Institution.all, :id, :name), {}, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group mb-3 actions">
      <%= form.submit 'Save' , class: 'btn btn-primary'%>
    </div>
<% end %>
</div>

app/views/students/_search_form.html.erb
<%= form_with url: students_path, local: true do |f| %>
  <div class="form-row align-items-center">
    <div class="col-sm-3 mb-3">
      <%= text_field_tag(:student_name, '', class: "form-control", placeholder: "Student name") %>
    </div>
    <div class="col-sm-3 mb-3">
      <%= text_field_tag(:institution_name, '', class: "form-control", placeholder: "Institution") %>
    </div>
    <div class="col-auto mb-3">
      <%= button_tag 'Search', class: "btn btn-primary" %>
    </div>
  </div>  
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<%= render "search_form" %>

<table class='table'>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Institution</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.full_name %></td>
        <td><%= student.address %></td>
        <td><%= student.mobile %></td>
        <td><%= student.institution.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @student.full_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @student.mobile %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @student.institution.try(:name) %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>